export const ADDFORMATION = "ADDFORMATION";
export const ADD_FORMATION_SUCCES = "ADD_FORMATION_SUCCES";
export const ADD_FORMATION_FAIL = "ADD_FORMATION_FAIL";

export const GETFORMATION = "GETFORMATION";

export const FORMATION_DELETE = "FORMATION_DELETE";
export const DELETE_FORMATION_SUCCES = "DELETE_FORMATION_SUCCES";
export const DELETE_FORMATION_FAIL = "DELETE_FORMATION_FAIL";

export const EDIT_FORMATION = "EDIT_FORMATION";
export const EDIT_FORMATION_SUCCES = "EDIT_FORMATION_SUCCES";
export const EDIT_FORMATION_FAIL = "EDIT_FORMATION_FAIL";